<?php declare(strict_types=1);session_start();header('Content-Type: application/json');$origin=$_SERVER['HTTP_ORIGIN']??'http://localhost:5173';header("Access-Control-Allow-Origin: $origin");header('Access-Control-Allow-Credentials: true');header('Access-Control-Allow-Headers: Content-Type');header('Access-Control-Allow-Methods: GET,POST,PATCH,OPTIONS');if($_SERVER['REQUEST_METHOD']==='OPTIONS'){http_response_code(204);exit;}$db=new PDO('sqlite:'.__DIR__.'/social.sqlite');$db->setAttribute(PDO::ATTR_ERRMODE,PDO::ERRMODE_EXCEPTION);$db->exec("PRAGMA foreign_keys=ON");$db->exec("CREATE TABLE IF NOT EXISTS users(id INTEGER PRIMARY KEY AUTOINCREMENT,name TEXT NOT NULL,email TEXT UNIQUE NOT NULL,password TEXT NOT NULL,bio TEXT DEFAULT '',avatar TEXT DEFAULT '',created_at TEXT NOT NULL);CREATE TABLE IF NOT EXISTS posts(id INTEGER PRIMARY KEY AUTOINCREMENT,user_id INTEGER NOT NULL,body TEXT NOT NULL,image TEXT DEFAULT '',created_at TEXT NOT NULL,FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE);CREATE TABLE IF NOT EXISTS reactions(id INTEGER PRIMARY KEY AUTOINCREMENT,post_id INTEGER NOT NULL,user_id INTEGER NOT NULL,reaction TEXT NOT NULL,UNIQUE(post_id,user_id));CREATE TABLE IF NOT EXISTS comments(id INTEGER PRIMARY KEY AUTOINCREMENT,post_id INTEGER NOT NULL,user_id INTEGER NOT NULL,text TEXT NOT NULL,created_at TEXT NOT NULL);CREATE TABLE IF NOT EXISTS stories(id INTEGER PRIMARY KEY AUTOINCREMENT,user_id INTEGER NOT NULL,text TEXT NOT NULL,created_at TEXT NOT NULL);CREATE TABLE IF NOT EXISTS messages(id INTEGER PRIMARY KEY AUTOINCREMENT,from_user_id INTEGER NOT NULL,to_user_id INTEGER NOT NULL,text TEXT NOT NULL,created_at TEXT NOT NULL)");
function b(){return json_decode(file_get_contents('php://input'),true)??[];}function out($x,$s=200){http_response_code($s);echo json_encode($x);exit;}function me(){global$db;if(empty($_SESSION['user_id']))out(['error'=>'Authentication required'],401);$q=$db->prepare('SELECT id,name,email,bio,avatar,created_at FROM users WHERE id=?');$q->execute([$_SESSION['user_id']]);return$q->fetch(PDO::FETCH_ASSOC);}function pu($id){global$db;$q=$db->prepare('SELECT id,name,email,bio,avatar FROM users WHERE id=?');$q->execute([$id]);return$q->fetch(PDO::FETCH_ASSOC);}
$r=parse_url($_SERVER['REQUEST_URI'],PHP_URL_PATH);$m=$_SERVER['REQUEST_METHOD'];
try{
if($r==='/api/register'&&$m==='POST'){$x=b();if(strlen($x['password']??'')<6)out(['error'=>'Password must contain at least 6 characters'],422);$q=$db->prepare('INSERT INTO users(name,email,password,created_at)VALUES(?,?,?,?)');$q->execute([trim($x['name']??''),strtolower(trim($x['email']??'')),password_hash($x['password'],PASSWORD_DEFAULT),date('c')]);$_SESSION['user_id']=$db->lastInsertId();out(['user'=>me()]);}
if($r==='/api/login'&&$m==='POST'){$x=b();$q=$db->prepare('SELECT * FROM users WHERE email=?');$q->execute([strtolower(trim($x['email']??''))]);$u=$q->fetch(PDO::FETCH_ASSOC);if(!$u||!password_verify($x['password']??'',$u['password']))out(['error'=>'Invalid credentials'],401);$_SESSION['user_id']=$u['id'];out(['user'=>me()]);}
if($r==='/api/logout'&&$m==='POST'){session_destroy();out(['ok'=>true]);}
if($r==='/api/me'&&$m==='GET')out(['user'=>me()]);
if($r==='/api/me'&&$m==='PATCH'){$u=me();$x=b();$q=$db->prepare('UPDATE users SET bio=?,avatar=? WHERE id=?');$q->execute([$x['bio']??$u['bio'],$x['avatar']??$u['avatar'],$u['id']]);out(['user'=>me()]);}
if($r==='/api/users'&&$m==='GET'){me();out(['users'=>$db->query('SELECT id,name,bio,avatar FROM users ORDER BY name')->fetchAll(PDO::FETCH_ASSOC)]);}
if($r==='/api/posts'&&$m==='GET'){me();$ps=$db->query('SELECT p.*,u.id uid,u.name,u.email,u.bio,u.avatar,(SELECT COUNT(*) FROM reactions r WHERE r.post_id=p.id) likes FROM posts p JOIN users u ON u.id=p.user_id ORDER BY p.id DESC LIMIT 50')->fetchAll(PDO::FETCH_ASSOC);foreach($ps as&$p){$q=$db->prepare('SELECT c.*,u.name,u.avatar FROM comments c JOIN users u ON u.id=c.user_id WHERE c.post_id=? ORDER BY c.id');$q->execute([$p['id']]);$p['comments']=$q->fetchAll(PDO::FETCH_ASSOC);$p['user']=['id'=>$p['uid'],'name'=>$p['name'],'email'=>$p['email'],'bio'=>$p['bio'],'avatar'=>$p['avatar']];}out(['posts'=>$ps]);}
if($r==='/api/posts'&&$m==='POST'){$u=me();$x=b();if(!trim($x['body']??''))out(['error'=>'Post text is required'],422);$q=$db->prepare('INSERT INTO posts(user_id,body,image,created_at)VALUES(?,?,?,?)');$q->execute([$u['id'],trim($x['body']),$x['image']??'',date('c')]);out(['ok'=>true]);}
if(preg_match('#^/api/posts/(\d+)/react$#',$r,$x)&&$m==='POST'){$u=me();$q=$db->prepare('INSERT INTO reactions(post_id,user_id,reaction)VALUES(?,?,?) ON CONFLICT(post_id,user_id) DO UPDATE SET reaction=excluded.reaction');$q->execute([(int)$x[1],$u['id'],b()['reaction']??'like']);out(['ok'=>true]);}
if(preg_match('#^/api/posts/(\d+)/comments$#',$r,$x)&&$m==='POST'){$u=me();$q=$db->prepare('INSERT INTO comments(post_id,user_id,text,created_at)VALUES(?,?,?,?)');$q->execute([(int)$x[1],$u['id'],trim(b()['text']??''),date('c')]);out(['ok'=>true]);}
if($r==='/api/stories'&&$m==='GET'){me();$a=$db->query("SELECT s.*,u.id uid,u.name,u.avatar FROM stories s JOIN users u ON u.id=s.user_id WHERE datetime(s.created_at)>=datetime('now','-1 day') ORDER BY s.id DESC")->fetchAll(PDO::FETCH_ASSOC);foreach($a as&$s)$s['user']=['id'=>$s['uid'],'name'=>$s['name'],'avatar'=>$s['avatar']];out(['stories'=>$a]);}
if($r==='/api/stories'&&$m==='POST'){$u=me();$x=b();$q=$db->prepare('INSERT INTO stories(user_id,text,created_at)VALUES(?,?,?)');$q->execute([$u['id'],trim($x['text']??''),date('c')]);out(['ok'=>true]);}
if($r==='/api/messages'&&$m==='GET'){$u=me();$id=(int)($_GET['user_id']??0);$q=$db->prepare('SELECT * FROM messages WHERE (from_user_id=? AND to_user_id=?) OR(from_user_id=? AND to_user_id=?) ORDER BY id');$q->execute([$u['id'],$id,$id,$u['id']]);out(['messages'=>$q->fetchAll(PDO::FETCH_ASSOC)]);}
if($r==='/api/messages'&&$m==='POST'){$u=me();$x=b();$q=$db->prepare('INSERT INTO messages(from_user_id,to_user_id,text,created_at)VALUES(?,?,?,?)');$q->execute([$u['id'],(int)$x['to_user_id'],trim($x['text']??''),date('c')]);out(['ok'=>true]);}
out(['error'=>'Not found'],404);
}catch(Throwable $e){out(['error'=>'Server error'],500);}