<?php declare(strict_types=1);

$path = parse_url($_SERVER['REQUEST_URI'] ?? '/', PHP_URL_PATH);
$method = $_SERVER['REQUEST_METHOD'];
$r = is_string($path) ? $path : '/';
$m = $method;

if ($path === '/health.php' && $method === 'GET') {
    out(['status' => 'ok']);
}

if (in_array($method, ['POST', 'PATCH', 'DELETE'], true) && $path !== '/api/login' && $path !== '/api/register') {
    csrf();
}

require_once __DIR__ . '/src/Http/Routes/AuthRoutes.php';

if (handleAuthRoutes($r, $m)) {
    exit;
}
require_once __DIR__ . '/src/Http/Routes/UserRoutes.php';

if (handleUserRoutes($r, $m)) {
    exit;
}

try{
if($r==='/api/media'&&$m==='POST'){ $u=me();rateLimit('media',(string)$u['id'],20,3600);if(empty($_FILES['file'])||$_FILES['file']['error']!==UPLOAD_ERR_OK)out(['error'=>'Upload failed'],422);$file=$_FILES['file'];if($file['size']>5242880)out(['error'=>'Maximum file size is 5 MB'],422);$finfo=new finfo(FILEINFO_MIME_TYPE);$mime=$finfo->file($file['tmp_name']);$allowed=['image/jpeg'=>'jpg','image/png'=>'png','image/webp'=>'webp','image/gif'=>'gif'];if(!isset($allowed[$mime]))out(['error'=>'Unsupported image type'],422);$dir=__DIR__.'/uploads';if(!is_dir($dir)&&!mkdir($dir,0755,true))out(['error'=>'Upload storage unavailable'],500);$name=bin2hex(random_bytes(16)).'.'.$allowed[$mime];if(!move_uploaded_file($file['tmp_name'],$dir.'/'.$name))out(['error'=>'Unable to store upload'],500);out(['url'=>((isset($_SERVER['HTTPS'])&&$_SERVER['HTTPS']!=='off')?'https':'http').'://'.($_SERVER['HTTP_HOST']??'localhost').'/uploads/'.$name]);}
if($r==='/api/posts'&&$m==='GET'){$u=me();$page=max(1,(int)($_GET['page']??1));$limit=min(50,max(1,(int)($_GET['limit']??10)));$offset=($page-1)*$limit;$q=$db->prepare('SELECT p.*,u.id uid,u.name,u.bio,u.avatar,(SELECT COUNT(*) FROM reactions r WHERE r.post_id=p.id) likes FROM posts p JOIN users u ON u.id=p.user_id WHERE COALESCE((SELECT private_account FROM user_settings s WHERE s.user_id=p.user_id),0)=0 OR p.user_id=? OR EXISTS(SELECT 1 FROM follows f WHERE f.follower_id=? AND f.following_id=p.user_id) ORDER BY p.id DESC LIMIT ? OFFSET ?');$q->bindValue(1,$u['id'],PDO::PARAM_INT);$q->bindValue(2,$u['id'],PDO::PARAM_INT);$q->bindValue(3,$limit+1,PDO::PARAM_INT);$q->bindValue(4,$offset,PDO::PARAM_INT);$q->execute();$ps=$q->fetchAll(PDO::FETCH_ASSOC);$hasMore=count($ps)>$limit;if($hasMore)array_pop($ps);foreach($ps as&$p){$q=$db->prepare('SELECT c.*,u.name,u.avatar FROM comments c JOIN users u ON u.id=c.user_id WHERE c.post_id=? ORDER BY c.id');$q->execute([$p['id']]);$comments=$q->fetchAll(PDO::FETCH_ASSOC);foreach($comments as&$comment)$comment['user']=['id'=>$comment['user_id'],'name'=>$comment['name'],'avatar'=>$comment['avatar']];$p['comments']=$comments;$p['user']=['id'=>$p['uid'],'name'=>$p['name'],'bio'=>$p['bio'],'avatar'=>$p['avatar']];}out(['posts'=>$ps,'page'=>$page,'hasMore'=>$hasMore]);}
if($r==='/api/posts'&&$m==='POST'){$u=me();rateLimit('post',(string)$u['id'],30,3600);$x=b();$body=trim((string)($x['body']??''));if($body===''||mb_strlen($body)>5000)out(['error'=>'Post text must contain between 1 and 5000 characters'],422);$q=$db->prepare('INSERT INTO posts(user_id,body,image,created_at)VALUES(?,?,?,?)');$q->execute([$u['id'],$body,trim((string)($x['image']??'')),date('c')]);out(['ok'=>true]);}
if(preg_match('#^/api/posts/(\d+)$#',$r,$x)&&in_array($m,['PATCH','DELETE'],true)){$u=me();$postId=(int)$x[1];$owner=$db->prepare('SELECT user_id FROM posts WHERE id=?');$owner->execute([$postId]);$ownerId=(int)$owner->fetchColumn();if(!$ownerId)out(['error'=>'Post not found'],404);if($ownerId!==$u['id'])out(['error'=>'Forbidden'],403);if($m==='DELETE'){$db->beginTransaction();try{$q=$db->prepare('DELETE FROM reactions WHERE post_id=?');$q->execute([$postId]);$q=$db->prepare('DELETE FROM comments WHERE post_id=?');$q->execute([$postId]);$q=$db->prepare('DELETE FROM notifications WHERE post_id=?');$q->execute([$postId]);$q=$db->prepare('DELETE FROM posts WHERE id=?');$q->execute([$postId]);$db->commit();out(['ok'=>true]);}catch(Throwable $e){$db->rollBack();throw $e;}}$x=b();$body=trim((string)($x['body']??''));if($body===''||mb_strlen($body)>5000)out(['error'=>'Post text must contain between 1 and 5000 characters'],422);$q=$db->prepare('UPDATE posts SET body=?,image=? WHERE id=?');$q->execute([$body,$x['image']??'',$postId]);out(['ok'=>true]);}
if(preg_match('#^/api/posts/(\d+)/react$#',$r,$x)&&$m==='POST'){$u=me();$postId=(int)$x[1];if(!canViewPost($postId,(int)$u['id']))out(['error'=>'Post not found'],404);$payload=b();$reaction=(string)($payload['reaction']??'like');if(!in_array($reaction,['like','love','laugh','wow','sad','angry'],true))out(['error'=>'Unsupported reaction'],422);$q=$db->prepare('INSERT INTO reactions(post_id,user_id,reaction)VALUES(?,?,?) ON CONFLICT(post_id,user_id) DO UPDATE SET reaction=excluded.reaction');$q->execute([$postId,$u['id'],$reaction]);$owner=$db->prepare('SELECT user_id FROM posts WHERE id=?');$owner->execute([$postId]);$ownerId=(int)$owner->fetchColumn();if($ownerId&&$ownerId!==$u['id']){$n=$db->prepare('INSERT INTO notifications(user_id,type,actor_id,post_id,created_at)VALUES(?,?,?,?,?)');$n->execute([$ownerId,'reacted_to_post',$u['id'],$postId,date('c')]);}out(['ok'=>true]);}
if(preg_match('#^/api/posts/(\d+)/comments$#',$r,$x)&&$m==='POST'){$u=me();$postId=(int)$x[1];if(!canViewPost($postId,(int)$u['id']))out(['error'=>'Post not found'],404);$payload=b();$text=trim((string)($payload['text']??''));if($text===''||mb_strlen($text)>2000)out(['error'=>'Comment must contain between 1 and 2000 characters'],422);rateLimit('comment',(string)$u['id'],60,3600);$q=$db->prepare('INSERT INTO comments(post_id,user_id,text,created_at)VALUES(?,?,?,?)');$q->execute([$postId,$u['id'],$text,date('c')]);$owner=$db->prepare('SELECT user_id FROM posts WHERE id=?');$owner->execute([$postId]);$ownerId=(int)$owner->fetchColumn();if($ownerId&&$ownerId!==$u['id']){$n=$db->prepare('INSERT INTO notifications(user_id,type,actor_id,post_id,created_at)VALUES(?,?,?,?,?)');$n->execute([$ownerId,'commented_on_post',$u['id'],$postId,date('c')]);}out(['ok'=>true]);}
if(preg_match('#^/api/comments/(\d+)$#',$r,$x)&&in_array($m,['PATCH','DELETE'],true)){$u=me();$commentId=(int)$x[1];$owner=$db->prepare('SELECT user_id FROM comments WHERE id=?');$owner->execute([$commentId]);$ownerId=(int)$owner->fetchColumn();if(!$ownerId)out(['error'=>'Comment not found'],404);if($ownerId!==$u['id'])out(['error'=>'Forbidden'],403);if($m==='DELETE'){$q=$db->prepare('DELETE FROM comments WHERE id=?');$q->execute([$commentId]);out(['ok'=>true]);}$payload=b();$text=trim((string)($payload['text']??''));if($text===''||mb_strlen($text)>2000)out(['error'=>'Comment must contain between 1 and 2000 characters'],422);$q=$db->prepare('UPDATE comments SET text=? WHERE id=?');$q->execute([$text,$commentId]);out(['ok'=>true]);}
if($r==='/api/stories'&&$m==='GET'){$u=me();$q=$db->prepare("SELECT s.*,u.id uid,u.name,u.avatar FROM stories s JOIN users u ON u.id=s.user_id WHERE datetime(s.created_at)>=datetime('now','-1 day') AND (COALESCE((SELECT private_account FROM user_settings s2 WHERE s2.user_id=s.user_id),0)=0 OR s.user_id=? OR EXISTS(SELECT 1 FROM follows f WHERE f.follower_id=? AND f.following_id=s.user_id)) ORDER BY s.id DESC");$q->execute([$u['id'],$u['id']]);$a=$q->fetchAll(PDO::FETCH_ASSOC);foreach($a as&$s)$s['user']=['id'=>$s['uid'],'name'=>$s['name'],'avatar'=>$s['avatar']];out(['stories'=>$a]);}
if($r==='/api/stories'&&$m==='POST'){$u=me();rateLimit('story',(string)$u['id'],20,86400);$x=b();$text=trim((string)($x['text']??''));if($text===''||mb_strlen($text)>1000)out(['error'=>'Story text is required'],422);$q=$db->prepare('INSERT INTO stories(user_id,text,created_at)VALUES(?,?,?)');$q->execute([$u['id'],$text,date('c')]);out(['ok'=>true]);}
if($r==='/api/messages'&&$m==='GET'){$u=me();$id=(int)($_GET['user_id']??0);if($id<=0||$id===$u['id'])out(['error'=>'A conversation participant is required'],422);$q=$db->prepare('SELECT id FROM users WHERE id=?');$q->execute([$id]);if(!$q->fetchColumn())out(['error'=>'User not found'],404);$q=$db->prepare('SELECT * FROM messages WHERE (from_user_id=? AND to_user_id=?) OR(from_user_id=? AND to_user_id=?) ORDER BY id');$q->execute([$u['id'],$id,$id,$u['id']]);out(['messages'=>$q->fetchAll(PDO::FETCH_ASSOC)]);}
if($r==='/api/messages'&&$m==='POST'){$u=me();rateLimit('message',(string)$u['id'],120,3600);$x=b();$to=(int)($x['to_user_id']??0);$text=trim($x['text']??'');if(!$to||$to===$u['id']||$text===''||mb_strlen($text)>4000)out(['error'=>'A valid message recipient and text are required'],422);$recipient=$db->prepare('SELECT id FROM users WHERE id=?');$recipient->execute([$to]);if(!$recipient->fetchColumn())out(['error'=>'User not found'],404);$q=$db->prepare('INSERT INTO messages(from_user_id,to_user_id,text,created_at)VALUES(?,?,?,?)');$q->execute([$u['id'],$to,$text,date('c')]);$n=$db->prepare('INSERT INTO notifications(user_id,type,actor_id,created_at)VALUES(?,?,?,?)');$n->execute([$to,'sent_you_a_message',$u['id'],date('c')]);out(['ok'=>true]);}
if(preg_match('#^/api/users/(\d+)/follow$#',$r,$x)&&in_array($m,['POST','DELETE'],true)){ $u=me();$target=(int)$x[1];if($target===$u['id'])out(['error'=>'Cannot follow yourself'],422);$q=$db->prepare('SELECT id FROM users WHERE id=?');$q->execute([$target]);if(!$q->fetchColumn())out(['error'=>'User not found'],404);if($m==='POST'){$q=$db->prepare('INSERT OR IGNORE INTO follows(follower_id,following_id,created_at)VALUES(?,?,?)');$q->execute([$u['id'],$target,date('c')]);if($q->rowCount()===0)out(['ok'=>true]);$n=$db->prepare('INSERT INTO notifications(user_id,type,actor_id,created_at)VALUES(?,?,?,?)');$n->execute([$target,'started_following_you',$u['id'],date('c')]);}else{$q=$db->prepare('DELETE FROM follows WHERE follower_id=? AND following_id=?');$q->execute([$u['id'],$target]);}out(['ok'=>true]);}
if(preg_match('#^/api/users/(\d+)/(followers|following)$#',$r,$x)&&$m==='GET'){me();$id=(int)$x[1];$join=$x[2]==='followers'?'follower_id':'following_id';$column=$x[2]==='followers'?'following_id':'follower_id';$q=$db->prepare('SELECT u.id,u.name,u.avatar FROM follows f JOIN users u ON u.id=f.'.$join.' WHERE f.'.$column.'=? ORDER BY u.name');$q->execute([$id]);out(['users'=>$q->fetchAll(PDO::FETCH_ASSOC)]);}
if(preg_match('#^/api/stories/(\d+)/view$#',$r,$x)&&$m==='POST'){ $u=me();$storyId=(int)$x[1];$q=$db->prepare("SELECT s.user_id,COALESCE((SELECT private_account FROM user_settings s2 WHERE s2.user_id=s.user_id),0) private_account FROM stories s WHERE s.id=?");$q->execute([$storyId]);$story=$q->fetch(PDO::FETCH_ASSOC);if(!$story)out(['error'=>'Story not found'],404);if((bool)$story['private_account']&&(int)$story['user_id']!==(int)$u['id']){$follow=$db->prepare('SELECT 1 FROM follows WHERE follower_id=? AND following_id=?');$follow->execute([$u['id'],(int)$story['user_id']]);if(!$follow->fetchColumn())out(['error'=>'Story not found'],404);}$q=$db->prepare('INSERT OR IGNORE INTO story_views(story_id,user_id,created_at)VALUES(?,?,?)');$q->execute([$storyId,$u['id'],date('c')]);out(['ok'=>true]);}
if(preg_match('#^/api/notifications/(\d+)/read$#',$r,$x)&&$m==='POST'){ $u=me();$q=$db->prepare('UPDATE notifications SET read_at=? WHERE id=? AND user_id=?');$q->execute([date('c'),(int)$x[1],$u['id']]);out(['ok'=>true]);}
if($r==='/api/notifications'&&$m==='GET'){$u=me();$q=$db->prepare('SELECT n.*,u.id uid,u.name,u.avatar,u.bio FROM notifications n JOIN users u ON u.id=n.actor_id WHERE n.user_id=? ORDER BY n.id DESC LIMIT 30');$q->execute([$u['id']]);$items=$q->fetchAll(PDO::FETCH_ASSOC);foreach($items as&$n)$n['actor']=['id'=>$n['uid'],'name'=>$n['name'],'avatar'=>$n['avatar'],'bio'=>$n['bio']];out(['notifications'=>$items]);}out(['error'=>'Not found'],404);
}catch(Throwable $e){out(['error'=>'Server error'],500);}