import type { Message, Notification, Post, Story, User } from "../types";
const API=import.meta.env.VITE_API_URL||"http://localhost:8080"; let csrfToken="";
async function request<T>(path:string,options:RequestInit={}):Promise<T>{const response=await fetch(API+path,{credentials:"include",headers:{"Content-Type":"application/json",...(csrfToken?{"X-CSRF-Token":csrfToken}:{}),...(options.headers||{})},...options});const data=await response.json();if(!response.ok)throw new Error(data.error||"Request failed");return data as T;}
export const api={me:async()=>{const r=await request<{user:User;csrf:string}>("/api/me");csrfToken=r.csrf;return r},login:async(email:string,password:string)=>{const r=await request<{user:User;csrf:string}>("/api/login",{method:"POST",body:JSON.stringify({email,password})});csrfToken=r.csrf;return r},register:async(name:string,email:string,password:string)=>{const r=await request<{user:User;csrf:string}>("/api/register",{method:"POST",body:JSON.stringify({name,email,password})});csrfToken=r.csrf;return r},logout:()=>request<{ok:boolean}>("/api/logout",{method:"POST"}),posts:(page=1,limit=10)=>request<{posts:Post[];page:number;hasMore:boolean}>("/api/posts?page="+page+"&limit="+limit),createPost:(body:string,image:string="")=>request<{ok:boolean}>("/api/posts",{method:"POST",body:JSON.stringify({body,image})}),
  updatePost:(id:number,body:string,image:string="")=>request<{ok:boolean}>("/api/posts/"+id,{method:"PATCH",body:JSON.stringify({body,image})}),
  deletePost:(id:number)=>request<{ok:boolean}>("/api/posts/"+id,{method:"DELETE"}),react:(id:number,reaction:string)=>request<{ok:boolean}>("/api/posts/"+id+"/react",{method:"POST",body:JSON.stringify({reaction})}),comment:(id:number,text:string)=>request<{ok:boolean}>("/api/posts/"+id+"/comments",{method:"POST",body:JSON.stringify({text})}),
  updateComment:(id:number,text:string)=>request<{ok:boolean}>("/api/comments/"+id,{method:"PATCH",body:JSON.stringify({text})}),
  deleteComment:(id:number)=>request<{ok:boolean}>("/api/comments/"+id,{method:"DELETE"}),stories:()=>request<{stories:Story[]}>("/api/stories"),createStory:(text:string)=>request<{ok:boolean}>("/api/stories",{method:"POST",body:JSON.stringify({text})}),users:(q="")=>request<{users:User[]}>("/api/users?q="+encodeURIComponent(q)),messages:(userId:number)=>request<{messages:Message[]}>("/api/messages?user_id="+userId),sendMessage:(to_user_id:number,text:string)=>request<{ok:boolean}>("/api/messages",{method:"POST",body:JSON.stringify({to_user_id,text})}),notifications:()=>request<{notifications:Notification[]}>("/api/notifications"),
  markNotificationRead:(id:number)=>request<{ok:boolean}>("/api/notifications/"+id+"/read",{method:"POST"}),
  follow:(id:number)=>request<{ok:boolean}>("/api/users/"+id+"/follow",{method:"POST"}),
  unfollow:(id:number)=>request<{ok:boolean}>("/api/users/"+id+"/follow",{method:"DELETE"}),
  storyView:(id:number)=>request<{ok:boolean}>("/api/stories/"+id+"/view",{method:"POST"}),updateProfile:(bio:string,avatar:string)=>request<{user:User}>("/api/me",{method:"PATCH",body:JSON.stringify({bio,avatar})}),
  settings:()=>request<{settings:{private_account:boolean;email_notifications:boolean}}>("/api/settings"),
  updateSettings:(settings:{private_account:boolean;email_notifications:boolean})=>request<{ok:boolean}>("/api/settings",{method:"PATCH",body:JSON.stringify(settings)}),
  uploadMedia:async(file:File)=>{const form=new FormData();form.append("file",file);const response=await fetch(API+"/api/media",{method:"POST",credentials:"include",headers:csrfToken?{"X-CSRF-Token":csrfToken}:undefined,body:form});const data=await response.json();if(!response.ok)throw new Error(data.error||"Upload failed");return data as {url:string};}};
